-- Per-user data: queues, favorites, plays, now playing, and what a sync has
-- already applied. docs/plans/006_api_and_sync.md

-- Bumped on every change to this user's data; objects carry the version they
-- last changed at, so a pull is "everything with version > my cursor".
ALTER TABLE users ADD COLUMN data_version INTEGER NOT NULL DEFAULT 0;

-- A queue's ID is generated by the client, so a queue created offline can be
-- referred to by later operations before the server has seen it.
CREATE TABLE queues (
    id          TEXT    NOT NULL PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        TEXT    NOT NULL,
    -- Song IDs in play order, as a JSON array. A queue holds at most a few
    -- thousand songs; one row per queue keeps every edit a single update.
    songs       TEXT    NOT NULL DEFAULT '[]',
    current_song INTEGER NOT NULL DEFAULT 0,
    position_ms  INTEGER NOT NULL DEFAULT 0,
    current_at   TEXT    NOT NULL DEFAULT '', -- when current_song/position last changed
    shuffle     INTEGER NOT NULL DEFAULT 0,
    repeat      TEXT    NOT NULL DEFAULT 'off', -- off | queue | song
    created_at  TEXT    NOT NULL,
    used_at     TEXT    NOT NULL, -- least recently used goes first past 20
    deleted     INTEGER NOT NULL DEFAULT 0,
    version     INTEGER NOT NULL
);
CREATE INDEX queues_user ON queues (user_id, version);

CREATE TABLE favorites (
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    song_id INTEGER NOT NULL REFERENCES songs (id),
    at      TEXT    NOT NULL, -- of the latest set/unset; the later one wins
    deleted INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL,
    PRIMARY KEY (user_id, song_id)
);

-- Append-only; counts, last played and most played are queries over this.
CREATE TABLE plays (
    id        INTEGER PRIMARY KEY,
    user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    song_id   INTEGER NOT NULL REFERENCES songs (id),
    device_id INTEGER,
    at        TEXT    NOT NULL,
    ms_played INTEGER NOT NULL
);
CREATE INDEX plays_user_song ON plays (user_id, song_id);

-- What hand-off reads (docs/plans/002_sync_and_handoff.md).
CREATE TABLE now_playing (
    user_id     INTEGER NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    device_id   INTEGER NOT NULL,
    device_name TEXT    NOT NULL,
    queue_id    TEXT    NOT NULL,
    song_id     INTEGER NOT NULL,
    position_ms INTEGER NOT NULL,
    playing     INTEGER NOT NULL,
    at          TEXT    NOT NULL,
    version     INTEGER NOT NULL
);

-- Operation IDs already applied, so a retried sync applies nothing twice.
CREATE TABLE applied_ops (
    user_id    INTEGER NOT NULL,
    op_id      TEXT    NOT NULL,
    applied_at TEXT    NOT NULL,
    PRIMARY KEY (user_id, op_id)
);

-- Lets an operation in the same batch refer to a playlist it just created
-- offline, before the client knows the server's integer ID.
ALTER TABLE playlists ADD COLUMN client_ref TEXT;
CREATE UNIQUE INDEX playlists_client_ref ON playlists (client_ref) WHERE client_ref IS NOT NULL;
